feat: add infinite scrolling to ADataTable
cisco-sbg-ui/atomic-react pull request #1174
Opened 2022-03-21 18:50 UTC by brennarvo

**Please check if the PR fulfills these requirements**
- [x] Create React hook for using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
- [x] Create a wrapper component that uses an intersection observer on it's direct children
- [x] Add infinite scrolling into the `ADataTable`
- [x] Documentation
- [ ] Infinite scrolling cypress tests
- [ ] Accessibility audit

**What kind of change does this PR introduce?** 

* Introduces a new `AInView` component to determine if some target element is currently visible within a specified scrollable container (such as the browser viewport itself).
* Adds two props to `ADataTable`:
  * `onScrollEnd: ({ inView, entry } : { inView: boolean, entry: IntersectionObserverEntry }) => void` - used when the target element toggles being inside/outside of the scrollable container
  * `maxHeight: string` - sets the maximum height of the data table to enable an overflow scroll for infinite scrolling
**What is the current behavior?** 

The `ADataTable` does not have functionality to support infinite scrolling.

**What is the new behavior (if this is a feature change)?**

Leverages the [Intersection Observer API]() in order to determine when the last row in the table is being viewed, which enables an external consumer of Atomic React to run a function that would (hypothetically) call the next batch of data table.

**Does this PR introduce a breaking change?** 

No

2022-03-23 15:51 UTC, trent-boyd commented on framework/components/AInView/AInView.spec.js
> +        cy.get(`${asyncUsageSelector} *[role="progressbar"]`).should("not.exist");
More Cypress options:

```js
cy.get(`${asyncUsageSelector} *[role="progressbar"]`).as("progressBar").should("not.exist");
// other things here...
cy.get("@progressBar").should("be.visible");
```

2022-03-23 15:53 UTC, trent-boyd commented on framework/utils/hooks.js
> +import {useCallback, useMemo, useEffect, useLayoutEffect, useRef, useState} from "react";
I got this far. Will review more later. :)

2022-03-30 17:46 UTC, rwharrisjr requested changes
Agreed with Trent's comments; lgtm otherwise.

2022-03-30 17:46 UTC, rwharrisjr commented on framework/components/ADataTable/ADataTable.js
> +        </ADataTableWrapper>
Needs to have a default `return null` if the return conditions are falsy.

2022-03-30 18:37 UTC, rwharrisjr approved these changes

2022-03-31 11:59 UTC, merged